image: elixir:1.9.4-alpine

services:
  - postgres:12.1-alpine

variables:
  POSTGRES_DB: diep_io_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  - cd server
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get --only test
  - mix ecto.setup

mix:
  script:
    - mix quality.ci
  cache:
    paths:
      - server/deps
      - server/priv/plts