import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :diep_io, DiepIOWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 80],
  # https: [
  #  port: 443,
  #  cipher_suite: :strong,
  #  keyfile: "priv/cert/selfsigned_key.pem",
  #  certfile: "priv/cert/selfsigned.pem"
  # ],
  check_origin: true

# Do not print debug messages in production
config :logger, level: :info
