"""
Simple script that generates GitLab project badges (in svg format) for the real time constraints of the system.
The script reads data from the json files in the `badges` folder of the project, and stores the generated badges
in that same folder.
The json files should be generated by the real time tests that are run automatically by the CI. This script is not
intended to be run manually, except for testing purposes.
"""

import anybadge
import json


def generate_badge(filename, label, thresholds, stat_key, format=''):
    data_file_name = f'badges/{filename}.json'
    try:
        with open(data_file_name) as f:
            val = json.load(f)[stat_key]

        badge = anybadge.Badge(
            label, val, thresholds=thresholds, value_suffix='ms', value_format=format)

        badge.write_badge(f'badges/{filename}.svg', True)
    except FileNotFoundError:
        print(f'{data_file_name} not found. Skipping badge generation.')
        pass

print('Generating badge for max iteration time')
thresholds = {101: 'green',
              201: 'yellow',
              334: 'orange',
              335: 'red'}
generate_badge('max_iteration_time', 'max iteration time', thresholds, 'max')

print('Generating badge for broadcast standard deviation')
thresholds = {2: 'green',
              4: 'yellow',
              6: 'orange',
              8: 'red'}
generate_badge('broadcast_std_dev', 'broadcast std dev',
               thresholds, 'std_dev', '%.2f')
