name: Build docker image

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Set image tag
      run: echo "IMAGE_TAG=ghcr.io/jdis/jdisgames-2020:$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
    
    - name: Login to ghcr
      run: docker login ghcr.io --username jdis-bot --password ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: ./server
      run: docker build . -t ${{ env.IMAGE_TAG }}

    - name: Push image
      run: docker push ${{ env.IMAGE_TAG }}
