name: Build docker image

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          echo ${SHORT_SHA}
          IMAGE_TAG="ghcr.io/jdis/jdisgames-2020:${SHORT_SHA}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo ${IMAGE_TAG}
      
      - name: Login to ghcr
        run: docker login ghcr.io --username jdis-bot --password ${{ github.token }}

      - name: Build Docker image
        working-directory: ./server
        run: docker build . -t ${{ env.IMAGE_TAG }}

      - name: Push image
        run: docker push ${{ env.IMAGE_TAG }}
